# 목표
프로젝트의 목표는 교통사고 데이터(RoadSense)를 기반으로 사고 심각도(Gravity)를 예측하는 모델을 개발하는 것입니다.     
최종적으로 사고 심각도를 조기에 예측할 수 있는 모델을 통해 교통 안전 개선 및 사고 예방 정책 수립에 데이터 기반 인사이트를 제공하는 것을 목표로 합니다.

### 데이터 셋 
실제 교통사고 데이터를 기반으로 교통사고 심각도 예측 Kaggle 대회용으로 수정된 데이터셋을 사용했습니다.    
사고 정보, 도로 정보, 차량 정보, 인적 요인 데이터셋으로 구성되어 있습니다.     
데이터 출처 : https://www.kaggle.com/competitions/etiq-roadsense

## DataPreprocessing의 목표
- 중복 데이터를 처리한다.
- Test 데이터를 기준으로 Train 데이터셋의 표기 형식을 통일한다.
> "RoadSense 데이터는 train/test로 분리 제공되며, test 데이터는 날짜·나이·좌석 위치 등의 표기 형식이 일관되게 정리되어 있는 반면     
> train 데이터는 형식이 혼재되어 있으므로, test 데이터의 표기 형식을 기준으로 train 데이터의 형식을 통일한다."

In [1]:
# 라이브러리

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import re
import string
from datetime import datetime

In [151]:
# 1. 데이터 로드 및 변수 저장

accidents_train = pd.read_csv('./data/accidents_train.csv')
places_train = pd.read_csv('./data/places_train.csv')
users_train = pd.read_csv('./data/users_train.csv')
vehicles_train = pd.read_csv('./data/vehicles_train.csv')

accidents_test = pd.read_csv('./data/accidents_test.csv')
places_test = pd.read_csv('./data/places_test.csv')
users_test = pd.read_csv('./data/users_test.csv')
vehicles_test = pd.read_csv('./data/vehicles_test.csv')

# 1. Accidents

- Accidents 데이터는 전체 분석의 기준이 되는 핵심 테이블이다.

## 데이터 확인
### 1) Test

In [152]:
# 데이터 확인
accidents_test.head(3)

,AccidentId,Date,Hour,Light,Department,Commune,InAgglomeration,IntersectionType,Weather,CollisionType,PostalAddress,GPSCode,Latitude,Longitude
0,201800000005,2018-06-26,16:05:00,Daylight,590,477,Yes,NoIntersection,Normal,2Vehicles-Side,72 rue Victor Hugo,M,50.51607,2.51607
1,201800000007,2018-09-26,00:40:00,NightStreelightsOn,590,133,Yes,NoIntersection,Normal,Other,4 route de camphin,M,50.52211,2.52211
2,201800000035,2018-03-16,21:15:00,NightNoStreetLight,590,581,No,NoIntersection,LightRain,Other,7 rue du pont de pierre,M,50.71101,2.71101

In [153]:
# 데이터 정보 확인
accidents_test.info()

<class 'pandas.DataFrame'>
RangeIndex: 5779 entries, 0 to 5778
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   AccidentId        5779 non-null   int64
 1   Date              5779 non-null   str
 2   Hour              5779 non-null   str
 3   Light             5779 non-null   str
 4   Department        5779 non-null   int64
 5   Commune           5779 non-null   int64
 6   InAgglomeration   5779 non-null   str
 7   IntersectionType  5779 non-null   str
 8   Weather           5779 non-null   str
 9   CollisionType     5779 non-null   str
 10  PostalAddress     5721 non-null   str
 11  GPSCode           5774 non-null   str
 12  Latitude          5577 non-null   float64
 13  Longitude         5577 non-null   float64
dtypes: float64(2), int64(3), str(9)
memory usage: 632.2 KB

In [154]:
# 결측치 확인
accidents_test.isna().sum()

AccidentId            0
Date                  0
Hour                  0
Light                 0
Department            0
Commune               0
InAgglomeration       0
IntersectionType      0
Weather               0
CollisionType         0
PostalAddress        58
GPSCode               5
Latitude            202
Longitude           202
dtype: int64

In [155]:
# 중복 데이터 갯수 확인
print(f"중복된 데이터 갯수: {accidents_test.duplicated().sum()}")

중복된 데이터 갯수: 0

In [156]:
# AccidentId 중복 데이터 갯수 확인
print(f"'AccidentId'기준 중복된 데이터 갯수: {accidents_test['AccidentId'].duplicated().sum()}")

'AccidentId'기준 중복된 데이터 갯수: 0

### 2) Train

In [157]:
# 데이터 확인
accidents_train.head(3)

,AccidentId,Gravity,Date,Hour,Light,Department,Commune,InAgglomeration,IntersectionType,Weather,CollisionType,PostalAddress,GPSCode,Latitude,Longitude
0,201800000001,NonLethal,24/01/2018,15:05:00,daylight,590,5,No,Y-type,Normal,2Vehicles-BehindVehicles-Frontal,route des Ansereuilles,M,50.555225,2.556955
1,201800000002,NonLethal,Feb 12 2018,10:15:00,Daylight,590,11,Yes,Square,VERYGOOD,NoCollision,Place du général de Gaul,M,50.529369,2.529158
2,201800000003,NonLethal,04-Mar-18,11:35:00:20,daylight,590,477,Yes,T-type,Normal,NoCollision,Rue nationale,M,50.510923,2.512682

In [158]:
# 데이터 정보 확인
accidents_train.info()

<class 'pandas.DataFrame'>
RangeIndex: 52004 entries, 0 to 52003
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   AccidentId        52004 non-null  str
 1   Gravity           47822 non-null  str
 2   Date              52004 non-null  str
 3   Hour              52004 non-null  str
 4   Light             52004 non-null  str
 5   Department        52004 non-null  int64
 6   Commune           52004 non-null  int64
 7   InAgglomeration   52004 non-null  str
 8   IntersectionType  52004 non-null  str
 9   Weather           51999 non-null  str
 10  CollisionType     52002 non-null  str
 11  PostalAddress     51507 non-null  str
 12  GPSCode           51959 non-null  str
 13  Latitude          50383 non-null  float64
 14  Longitude         50383 non-null  float64
dtypes: float64(2), int64(2), str(11)
memory usage: 6.0 MB

In [159]:
# 결측치 확인
accidents_train.isna().sum()

AccidentId             0
Gravity             4182
Date                   0
Hour                   0
Light                  0
Department             0
Commune                0
InAgglomeration        0
IntersectionType       0
Weather                5
CollisionType          2
PostalAddress        497
GPSCode               45
Latitude            1621
Longitude           1621
dtype: int64

In [160]:
# 중복 데이터 갯수 확인
print(f"중복된 데이터 갯수: {accidents_train.duplicated().sum()}")

중복된 데이터 갯수: 0

In [161]:
# AccidentId 중복 데이터 갯수 확인
print(f"'AccidentId'기준 중복된 데이터 갯수: {accidents_train['AccidentId'].duplicated().sum()}")

'AccidentId'기준 중복된 데이터 갯수: 0

In [162]:
accidents_train['Gravity'].unique()

<StringArray>
['NonLethal', nan, 'Lethal']
Length: 3, dtype: str

## 데이터 확인 결과
- Gravity는 이 데이터의 타깃 데이터이다. Gravity의 결측치는 타깃값이 없어 학습할 수 없으므로 제거한다.
- AccidentId, 날짜, 시간, 조명, 날씨 등 Test와는 다르게 표기 형식이 통일되지 않았으므로 이 값들을 통일시키는 작업부터 시작한다.

#### Gravity 결측치 제거

In [163]:
accidents_train = accidents_train.dropna(subset=['Gravity'])

In [164]:
# Gravity의 결측치 및 고유값 확인
print(f'남은 결측치 :\n{accidents_train.isna().sum()}\n')
print(f'고유값 : {accidents_train['Gravity'].unique()}')

남은 결측치 :
AccidentId             0
Gravity                0
Date                   0
Hour                   0
Light                  0
Department             0
Commune                0
InAgglomeration        0
IntersectionType       0
Weather                5
CollisionType          1
PostalAddress        455
GPSCode               42
Latitude            1507
Longitude           1507
dtype: int64

고유값 : <StringArray>
['NonLethal', 'Lethal']
Length: 2, dtype: str

#### AccidentId 컬럼
- '-' 하이픈 제거
- 공백 제거

In [165]:
# AccidentId 데이터 확인
accidents_train["AccidentId"].head(11)

0       201800000001
1       201800000002
2       201800000003
3       201800000004
5       201800000008
6       201800000009
8      201800000011
9       201800000012
10      201800000013
11     20-1800000014
12      201800000015
Name: AccidentId, dtype: str

In [166]:
# 하이픈 제거하기
accidents_train["AccidentId"] = accidents_train["AccidentId"].str.replace("-", "", regex = False)

In [167]:
# 공백 제거
accidents_train["AccidentId"] = accidents_train["AccidentId"].str.replace(" ", "", regex=False)

In [168]:
# AccidentId 데이터 확인
accidents_train["AccidentId"].head(11)

0     201800000001
1     201800000002
2     201800000003
3     201800000004
5     201800000008
6     201800000009
8     201800000011
9     201800000012
10    201800000013
11    201800000014
12    201800000015
Name: AccidentId, dtype: str

#### Date 컬럼
- 약어 제거
- 구분자 `/`, `' '`, `-` 등 `-`으로 통일
- 년-월-일 (YYYY-MM-DD) 순서 통일
- 시간데이터 제거

In [169]:
# Date 데이터 조회
accidents_train["Date"].head(10)

0              24/01/2018
1             Feb 12 2018
2               04-Mar-18
3             May 05 2018
5     2018-11-30 00:00:00
6             Feb 18 2018
8              28/05/2018
9             May 31 2018
10             15/06/2018
11    2018-07-19 00:00:00
Name: Date, dtype: str

In [170]:
# 약어 문자 숫자와 매핑
month_map = {
    'Jan':'01', 'Feb':'02', 'Mar':'03', 'Apr':'04',
    'May':'05', 'Jun':'06', 'Jul':'07', 'Aug':'08',
    'Sep':'09', 'Oct':'10', 'Nov':'11', 'Dec':'12'
}

In [171]:
# 약어 문자 숫자로 변환
accidents_train['Date'] = accidents_train['Date'].replace(month_map, regex=True)

**시간 미포함 데이터**
- 현 데이터는 2018년도 기준 데이터
- 구분자 '-'로 통일
- 시간 미포함 데이터는 맨뒤 날짜 포멧이 년도로 확인됨 (18 또는 2018)
- YYYY-MM-DD 형식을 맞추기위해 년도를 먼저 찾아서 2018년도 포맷을 맞춘다.
- 월/일 을 찾아서 YYYY-MM-DD 형식을 맞춰준다.

In [172]:
# 시간 미포함 mask 저장
mask_no_time = ~accidents_train["Date"].str.contains(r"\d{2}:\d{2}:\d{2}", na=False)

In [173]:
# 구분자 통일

accidents_train.loc[mask_no_time, "Date"] = (
    accidents_train.loc[mask_no_time, "Date"]
    .astype(str)
    .str.replace(r"[\/ ]", "-", regex=True)
)

In [174]:
# 시간 미포함 & '년도'가 맨뒤가 아닌 경우
accidents_train.loc[
    mask_no_time & ~accidents_train["Date"].astype(str).str.contains(r"(?:2018|18)$", na=False),"Date"
    ]

Series([], Name: Date, dtype: str)

In [175]:
# 18년도로 되어있는 년도를 2018로 수정

mask_18 = mask_no_time & accidents_train["Date"].str.contains(r"(?<!20)18$", na=False)

accidents_train.loc[mask_18, "Date"] = (
    accidents_train.loc[mask_18, "Date"].str.replace(r"18$", "2018", regex = True)
)

In [176]:
# 2018년도를 맨앞으로 이동하기
accidents_train.loc[mask_no_time, "Date"] = (
    accidents_train.loc[mask_no_time, "Date"].str.replace(r"^(\d{2})-(\d{2})-(2018)$", 
                                                          r"\3-\1-\2",
                                                          regex=True)
)

In [177]:
# 시간 미포함 기준 '월'이 12초과인 경우 mask 저장
mask_invalid_month = (
    mask_no_time &
    (accidents_train["Date"].str.extract(r"^2018-(\d{2})-(\d{2})")[0].astype(int) > 12)
)

In [178]:
# '월' 12 초과 자리 교체
accidents_train.loc[mask_invalid_month, "Date"] = (
    accidents_train.loc[mask_invalid_month, "Date"].str.replace(r"^2018-(\d{2})-(\d{2})$",
                                                                r"2018-\2-\1",
                                                                regex=True)
)

In [179]:
# 00:00:00 포맷 삭제하기

accidents_train["Date"] = (accidents_train["Date"].astype(str).str.replace(r"\s+\d{2}:\d{2}:\d{2}$", 
                                                                           "", 
                                                                           regex=True)
)

In [180]:
# 최종 변환 확인
accidents_train["Date"].head(10)

0     2018-01-24
1     2018-02-12
2     2018-04-03
3     2018-05-05
5     2018-11-30
6     2018-02-18
8     2018-05-28
9     2018-05-31
10    2018-06-15
11    2018-07-19
Name: Date, dtype: str

#### Hour 컬럼
- 초 이상의 포맷 (00:00:00:00) 삭제
- PM, AM 포맷 삭제
- 최종 `%H:%M:%S` 으로 통일

In [181]:
# Hour 데이터 조회
accidents_train["Hour"].head(10)

0        15:05:00
1        10:15:00
2     11:35:00:20
3         5:35 PM
5        17:15:00
6         3:57 PM
8        18:30:00
9     04:30:00:39
10       08:45:00
11    10:22:00:57
Name: Hour, dtype: str

In [182]:
#  콜론이 3개 이상 mask 생성
mask_colons = accidents_train["Hour"].str.count(":") > 2

In [183]:
# 00:00:00 포맷 맞추기
accidents_train.loc[mask_colons, "Hour"] = (
    accidents_train.loc[mask_colons, "Hour"].str.split(":").str[:3].str.join(":")
)

In [184]:
# AM / PM 을 24시간제로 통일하기
accidents_train["Hour"] = pd.to_datetime(accidents_train["Hour"],errors="coerce").dt.strftime("%H:%M:%S")

C:\Users\nini\AppData\Local\Temp\ipykernel_21888\1341841227.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  accidents_train["Hour"] = pd.to_datetime(accidents_train["Hour"],errors="coerce").dt.strftime("%H:%M:%S")

In [185]:
# 최종 변환 확인
accidents_train["Hour"].head(10)

0     15:05:00
1     10:15:00
2     11:35:00
3     17:35:00
5     17:15:00
6     15:57:00
8     18:30:00
9     04:30:00
10    08:45:00
11    10:22:00
Name: Hour, dtype: str

#### Light 컬럼
- 대소문자 표기 규칙 일치시키기
- 'Daylight', 'NightStreelightsOn', 'NightNoStreetLight', 'TwilightOrDawn', NightStreelightsOff'

In [186]:
# Light 데이터 조회
accidents_train["Light"].unique()

<StringArray>
[           'daylight',            'Daylight',            'DAYLIGHT',
  'NIGHTSTREELIGHTSON',  'NightNoStreetLight',      'TWILIGHTORDAWN',
      'twilightordawn',  'NIGHTNOSTREETLIGHT',  'nightstreelightson',
      'TwilightOrDawn',  'NightStreelightsOn',  'nightnostreetlight',
 'NIGHTSTREELIGHTSOFF', 'nightstreelightsoff', 'NightStreelightsOff']
Length: 15, dtype: str

In [187]:
# Light 모두 소문자로 변환하기
accidents_train["Light"] = accidents_train["Light"].str.lower()

In [188]:
# 매핑 테이블
light_mapping = {
    "daylight": "Daylight",
    "twilightordawn": "TwilightOrDawn",
    "nightstreelightson": "NightStreelightsOn",
    "nightnostreetlight": "NightNoStreetLight",
    "nightstreelightsoff": "NightStreelightsOff"
}

In [189]:
# 매핑 적용하기
accidents_train["Light"] = accidents_train["Light"].map(light_mapping)

In [190]:
# 최종 결과
accidents_train["Light"].unique()

<StringArray>
[           'Daylight',  'NightStreelightsOn',  'NightNoStreetLight',
      'TwilightOrDawn', 'NightStreelightsOff']
Length: 5, dtype: str

#### Weather 컬럼
- 대소문자 표기 규칙 일치시키기
- 'Normal', 'VeryGood', 'LightRain', 'FogOrSmoke', 'SnowOrHail', 'Overcast', 'Other', 'HeavyRain', 'StrongWindOrStorm'

In [191]:
# weather 데이터 조회
accidents_train["Weather"].unique()

<StringArray>
[           'Normal',          'VERYGOOD',        'FOGORSMOKE',
            'NORMAL',        'SnowOrHail',            'normal',
         'LightRain',        'snoworhail',          'Overcast',
          'VeryGood',         'lightrain',             'Other',
         'heavyrain',         'LIGHTRAIN',        'SNOWORHAIL',
             'OTHER',         'HEAVYRAIN', 'StrongWindOrStorm',
          'verygood',          'overcast',          'OVERCAST',
        'fogorsmoke',             'other',        'FogOrSmoke',
         'HeavyRain', 'strongwindorstorm', 'STRONGWINDORSTORM',
                 nan]
Length: 28, dtype: str

In [192]:
# Weather 모두 소문자로 변환
accidents_train["Weather"] = accidents_train["Weather"].str.lower()

In [193]:
# 매핑 테이블
Weather_mapping = {
    "normal": "Normal",
    "verygood": "VeryGood",
    "lightrain": "LightRain",
    "fogorsmoke": "FogOrSmoke",
    "snoworhail": "SnowOrHail",
    "overcast": "Overcast",
    "other": "Other",
    "heavyrain": "HeavyRain",
    "strongwindorstorm": "StrongWindOrStorm"
}

In [194]:
# 매핑 적용하기
accidents_train["Weather"] = accidents_train["Weather"].map(Weather_mapping)

In [195]:
accidents_train["Weather"].unique()

<StringArray>
[           'Normal',          'VeryGood',        'FogOrSmoke',
        'SnowOrHail',         'LightRain',          'Overcast',
             'Other',         'HeavyRain', 'StrongWindOrStorm',
                 nan]
Length: 10, dtype: str

# 2. Places

- Places 데이터는 사고장소의 정보를 담고 있는 테이블이다.

## 데이터 확인
### 1) Test

In [47]:
# 데이터 확인
places_test.head(3)

,AccidentId,RoadType,RoadNumber,RoadSecNumber,RoadLetter,Circulation,LaneNumber,SpecialLane,Slope,RoadMarkerId,RoadMarkerDistance,Layout,StripWidth,LaneWidth,SurfaceCondition,Infrastructure,Localization,SchoolNear
0,201800000005,Communal,NaN,NaN,NaN,OneWay,1.0,0,Flat,NaN,NaN,Straight,NaN,NaN,Normal,Unknown,Lane,0.0
1,201800000007,Departamental,41.0,NaN,D,TwoWay,2.0,0,Flat,16.0,500.0,Straight,NaN,NaN,Normal,Unknown,Shoulder,0.0
2,201800000035,Departamental,10.0,NaN,NaN,TwoWay,2.0,0,Flat,13.0,400.0,Straight,NaN,NaN,Wet,Unknown,Shoulder,0.0

In [48]:
# 데이터 정보 확인
places_test.info()

<class 'pandas.DataFrame'>
RangeIndex: 5779 entries, 0 to 5778
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   AccidentId          5779 non-null   int64
 1   RoadType            5779 non-null   str
 2   RoadNumber          3549 non-null   float64
 3   RoadSecNumber       18 non-null     float64
 4   RoadLetter          265 non-null    str
 5   Circulation         5740 non-null   str
 6   LaneNumber          5728 non-null   float64
 7   SpecialLane         5721 non-null   str
 8   Slope               5738 non-null   str
 9   RoadMarkerId        4204 non-null   float64
 10  RoadMarkerDistance  4169 non-null   float64
 11  Layout              5741 non-null   str
 12  StripWidth          1310 non-null   float64
 13  LaneWidth           1356 non-null   float64
 14  SurfaceCondition    5735 non-null   str
 15  Infrastructure      5730 non-null   str
 16  Localization        5732 non-null   str
 17  SchoolNear          5732 non-null   float64
dtypes: float64(8), int64(1), str(9)
memory usage: 812.8 KB

In [49]:
# 결측치 확인
places_test.isna().sum()

AccidentId               0
RoadType                 0
RoadNumber            2230
RoadSecNumber         5761
RoadLetter            5514
Circulation             39
LaneNumber              51
SpecialLane             58
Slope                   41
RoadMarkerId          1575
RoadMarkerDistance    1610
Layout                  38
StripWidth            4469
LaneWidth             4423
SurfaceCondition        44
Infrastructure          49
Localization            47
SchoolNear              47
dtype: int64

In [50]:
# 중복 데이터 갯수 확인
print(f"중복된 데이터 갯수: {places_test.duplicated().sum()}")

중복된 데이터 갯수: 0

In [51]:
# AccidentId 기준 중복 데이터 갯수 확인
print(f"'AccidentId'기준 중복된 데이터 갯수: {accidents_test['AccidentId'].duplicated().sum()}")

'AccidentId'기준 중복된 데이터 갯수: 0

### 2) Train

In [52]:
# 데이터 확인
places_train.head(3)

,AccidentId,RoadType,RoadNumber,RoadSecNumber,RoadLetter,Circulation,LaneNumber,SpecialLane,Slope,RoadMarkerId,RoadMarkerDistance,Layout,StripWidth,LaneWidth,SurfaceCondition,Infrastructure,Localization,SchoolNear
0,201800000001,Departamental,Route 41,NaN,C,TwoWay,2.0,0,Flat,NaN,NaN,RightCurve,NaN,NaN,Normal,Unknown,Lane,0.0
1,201800000002,Communal,Dept-41,NaN,D,TwoWay,2.0,0,Flat,NaN,NaN,LeftCurve,NaN,NaN,Normal,Unknown,Lane,0.0
2,201800000003,Departamental,D39,NaN,D,TwoWay,2.0,0,Flat,NaN,NaN,NaN,NaN,NaN,Normal,Unknown,Lane,0.0

In [53]:
# 데이터 정보 확인
places_train.info()

<class 'pandas.DataFrame'>
RangeIndex: 54604 entries, 0 to 54603
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   AccidentId          54604 non-null  str
 1   RoadType            54604 non-null  str
 2   RoadNumber          34017 non-null  str
 3   RoadSecNumber       153 non-null    float64
 4   RoadLetter          2701 non-null   str
 5   Circulation         54219 non-null  str
 6   LaneNumber          54125 non-null  float64
 7   SpecialLane         54116 non-null  str
 8   Slope               54187 non-null  str
 9   RoadMarkerId        39688 non-null  float64
 10  RoadMarkerDistance  39438 non-null  float64
 11  Layout              51133 non-null  str
 12  StripWidth          12579 non-null  float64
 13  LaneWidth           12975 non-null  float64
 14  SurfaceCondition    51121 non-null  str
 15  Infrastructure      51088 non-null  str
 16  Localization        54135 non-null  str
 17  SchoolNear          54174 non-null  float64
dtypes: float64(7), str(11)
memory usage: 7.5 MB

In [54]:
# 결측치 확인
places_train.isna().sum()

AccidentId                0
RoadType                  0
RoadNumber            20587
RoadSecNumber         54451
RoadLetter            51903
Circulation             385
LaneNumber              479
SpecialLane             488
Slope                   417
RoadMarkerId          14916
RoadMarkerDistance    15166
Layout                 3471
StripWidth            42025
LaneWidth             41629
SurfaceCondition       3483
Infrastructure         3516
Localization            469
SchoolNear              430
dtype: int64

In [55]:
# 중복 데이터 갯수 확인
print(f"중복된 데이터 갯수: {places_train.duplicated().sum()}")

# AccidentId 기준 중복 데이터 갯수 확인
print(f"'AccidentId'기준 중복된 데이터 갯수: {places_train['AccidentId'].duplicated().sum()}")

중복된 데이터 갯수: 735
'AccidentId'기준 중복된 데이터 갯수: 2600

## 데이터 확인 결과
- places_train 의 중복데이터가 존재한다.
- 표기형식이 통일되어있지 않는 컬럼이 존재한다.

#### 중복 데이터 삭제
- 중복 데이터를 삭제전 AccidentId를 기준으로 확인해야 하기 때문에 AccidentId의 표기 형식을 통일한다.

In [56]:
# AccidentId 데이터 확인
places_train["AccidentId"].head(10)

0     201800000001
1     201800000002
2     201800000003
3     201800000004
4     201800000006
5    20-1800000008
6    20-1800000009
7     201800000010
8     201800000011
9     201800000012
Name: AccidentId, dtype: str

In [57]:
places_train["AccidentId"] = places_train["AccidentId"].str.replace("-","", regex = False)

In [58]:
places_train["AccidentId"] = places_train["AccidentId"].str.replace(" ","", regex = False)

In [59]:
# 최종 확인
places_train["AccidentId"].head(10)

0    201800000001
1    201800000002
2    201800000003
3    201800000004
4    201800000006
5    201800000008
6    201800000009
7    201800000010
8    201800000011
9    201800000012
Name: AccidentId, dtype: str

In [60]:
# 중복된 행 제거 및 인덱스 정리
places_train = places_train.drop_duplicates().reset_index(drop=True)

In [61]:
# AccidentId 기준 중복 데이터 갯수 재확인
places_train['AccidentId'].duplicated().sum()

np.int64(1865)

In [62]:
#AccidentId 중복행 확인해보기 (AccidentId를 기준으로 오름차순 정렬)
places_train[places_train['AccidentId'].duplicated(keep=False)].sort_values('AccidentId').head(20)

,AccidentId,RoadType,RoadNumber,RoadSecNumber,RoadLetter,Circulation,LaneNumber,SpecialLane,Slope,RoadMarkerId,RoadMarkerDistance,Layout,StripWidth,LaneWidth,SurfaceCondition,Infrastructure,Localization,SchoolNear
16,201800000019,Departamental,145,NaN,NaN,TwoWay,2.0,0,Flat,NaN,NaN,Straight,NaN,NaN,NaN,Unknown,Lane,0.0
53801,201800000019,Departamental,Modified,NaN,NaN,TwoWay,2.0,0,Flat,NaN,NaN,Straight,NaN,NaN,Normal,Unknown,Lane,0.0
52350,201800000020,Modified,NaN,NaN,NaN,TwoWay,2.0,0,Flat,NaN,NaN,Unknown,NaN,NaN,Normal,Unknown,Lane,0.0
17,201800000020,Communal,NaN,NaN,NaN,TwoWay,2.0,0,Flat,NaN,NaN,LeftCurve,NaN,NaN,Normal,Unknown,Lane,0.0
91,201800000100,Departamental,115,NaN,NaN,TwoWay,2.0,0,Flat,5.0,1000.0,Straight,NaN,NaN,Normal,Unknown,Lane,0.0
53107,201800000100,Departamental,115,NaN,NaN,TwoWay,2.0,0,Flat,5.0,1000.0,Modified,NaN,NaN,Normal,NaN,Lane,0.0
129,201800000141,Departamental,938,NaN,NaN,TwoWay,2.0,0,Flat,NaN,NaN,Straight,NaN,NaN,Normal,Unknown,Lane,0.0
52628,201800000141,Departamental,938,NaN,NaN,TwoWay,2.0,0,Flat,NaN,NaN,Straight,NaN,NaN,Normal,Unknown,Modified,0.0
136,201800000149,Departamental,D938,NaN,NaN,TwoWay,2.0,0,Flat,NaN,NaN,Straight,NaN,NaN,0,Unknown,Lane,0.0
53207,201800000149,Departamental,D938,NaN,NaN,TwoWay,2.0,0,Flat,NaN,NaN,Modified,NaN,NaN,Normal,Unknown,Lane,0.0
141,201800000154,Communal,NaN,NaN,NaN,TwoWay,2.0,0,Flat,NaN,NaN,RightCurve,NaN,NaN,Wet,NaN,Lane,0.0
52527,201800000154,Communal,NaN,NaN,NaN,TwoWay,2.0,0,Flat,NaN,NaN,RightCurve,NaN,NaN,Wet,Unknown,Lane,0.0
157,201800000170,Highway,Dept-16,NaN,NaN,DividedHighway,4.0,0,Uphill,69.0,100.0,NaN,NaN,NaN,Normal,Unknown,Lane,0.0
52198,201800000170,Highway,Dept-16,NaN,NaN,DividedHighway,4.0,0,Modified,69.0,100.0,Straight,NaN,NaN,Normal,Unknown,Lane,0.0
163,201800000176,Departamental,Route 55,NaN,NaN,TwoWay,2.0,0,Flat,14.0,37.0,Unknown,NaN,NaN,Normal,Unknown,Lane,0.0
52367,201800000176,Departamental,Route 55,NaN,NaN,TwoWay,2.0,0,Flat,14.0,37.0,LeftCurve,NaN,NaN,Normal,Unknown,Lane,0.0
52521,201800000201,Departamental,D901,NaN,NaN,Modified,2.0,0,Flat,44.0,910.0,Straight,NaN,NaN,Normal,Unknown,Lane,0.0
185,201800000201,Departamental,D901,NaN,NaN,TwoWay,2.0,0,Flat,44.0,910.0,Straight,NaN,NaN,Normal,Unknown,Lane,0.0
53538,201800000219,PublicParking,NaN,NaN,NaN,NaN,NaN,0,Flat,NaN,NaN,Straight,NaN,NaN,Wet,Unknown,Lane,0.0
201,201800000219,PublicParking,NaN,NaN,NaN,NaN,NaN,0,Flat,NaN,NaN,NaN,NaN,NaN,Wet,Unknown,Lane,0.0

**문제 발견 및 원인 분석**

- 중복행은 대부분 컬럼에서 동일한 값을 가지고 있었으나 매번 서로 다른 컬럼에 'Modified'라는 문자열이 나타남
- 'Modified'는 비정상적인 카테고리 값으로 데이터 처리 과정에서 잘못 삽입된 오염값일 가능성이 있다고 판단함
- 중복행은 나머지 컬럼에서 서로 다른 결측 패턴을 보이며 정보를 상호 보완하는 관계였음

**해결 방법**

- drop_duplicates()를 사용하면 살아남지 못한 행이 가지고 있던 유효한 정보가 사라짐
- 이를 해결하기 위해 'Modified' 값을 NaN으로 치환하여 병합 단계에서 정상 값으로 채워질 수 있도록 함
- groupby("AccidentId").first()를 사용해 결측이 아닌 값을 우선적으로 채택해 하나의 행으로 병합함

In [63]:
# 병합 전 고유 AccidentId 고유값 확인
print(places_train['AccidentId'].nunique())

52004

In [64]:
# Modified를 NaN으로 처리하기
places_train = places_train.replace('Modified', np.nan)

In [65]:
# AccidentId를 기준으로 중복 행 .first() 함수를 사용해 병합하기
places_train = places_train.groupby('AccidentId', as_index=False).first()

In [66]:
# 병합 후 행 갯수 확인 (병합 전 AccidentId 고유값과 같아야함)
print(len(places_train))

52004

In [67]:
# 정상 값들로 잘 채워졌는지 중복행이였던 데이터 확인해보기
places_train[places_train['AccidentId'] == '201800000019']

,AccidentId,RoadType,RoadNumber,RoadSecNumber,RoadLetter,Circulation,LaneNumber,SpecialLane,Slope,RoadMarkerId,RoadMarkerDistance,Layout,StripWidth,LaneWidth,SurfaceCondition,Infrastructure,Localization,SchoolNear
16,201800000019,Departamental,145,NaN,NaN,TwoWay,2.0,0,Flat,NaN,NaN,Straight,NaN,NaN,Normal,Unknown,Lane,0.0

In [68]:
# 중복 데이터 갯수 확인
print(f"중복된 데이터 갯수: {places_train.duplicated().sum()}")

# AccidentId 기준 중복 데이터 갯수 확인
print(f"'AccidentId'기준 중복된 데이터 갯수: {places_train['AccidentId'].duplicated().sum()}")

중복된 데이터 갯수: 0
'AccidentId'기준 중복된 데이터 갯수: 0

#### RoadNumber 컬럼 (도로의 고유 번호)
- '-' 하이픈 및 문자열 제거
- Test와 동일하게 숫자로만 변환

In [69]:
# 데이터 확인
places_train["RoadNumber"].head(10)

0     Route 41
1      Dept-41
2          D39
3      Dept-39
4      Dept-39
5      Route -
6    Route 141
7         D641
8     Dept-641
9           41
Name: RoadNumber, dtype: str

In [70]:
# 문자 제거하기 및 빈값 NaN 변환하기
places_train["RoadNumber"] = (
    places_train["RoadNumber"].str.replace(r"[^0-9]", "", regex = True).replace("", np.nan))

In [71]:
# 최종 확인
places_train["RoadNumber"].head(10)

0     41
1     41
2     39
3     39
4     39
5    NaN
6    141
7    641
8    641
9     41
Name: RoadNumber, dtype: str

#### Layout(도로 형태), SurfaceCondition(도로 노면 상태), Infrastructure(도로 시설/구조물) 
- '-', '0' 값 NaN으로 변경

In [72]:
# 변경할 컬럼 변수 저장
cols = ["Layout", "SurfaceCondition", "Infrastructure"]

In [73]:
# 값 확인하기
places_train[cols].isin(["-","0"]).sum()

Layout              1464
SurfaceCondition    1634
Infrastructure      1482
dtype: int64

In [74]:
# '-' 수정
places_train[cols] = places_train[cols].replace("-", np.nan)

In [75]:
# '0' 수정
places_train[cols] = places_train[cols].replace("0", np.nan)

In [76]:
# 최종 변경 확인
places_train[cols].isin(["Modified","-","0"]).sum()

Layout              0
SurfaceCondition    0
Infrastructure      0
dtype: int64

In [77]:
# 최종 변경 후 중복데이터 확인
print(f"중복된 데이터 갯수: {places_train.duplicated().sum()}")

# AccidentId 기준 중복 데이터 갯수 확인
print(f"'AccidentId'기준 중복된 데이터 갯수: {places_train['AccidentId'].duplicated().sum()}")

중복된 데이터 갯수: 0
'AccidentId'기준 중복된 데이터 갯수: 0

# 3. Users

- Users는 사고에 관련된 인적 정보를 담고 있는 테이블이다.

## 데이터 확인
### 1) Test

In [78]:
# 데이터 확인
users_test.head(3)

,AccidentId,VehicleId,Seat,Category,Gender,TripReason,SafetyDevice,SafetyDeviceUsed,PedestrianLocation,PedestrianAction,PedestrianCompany,BirthYear
0,201800000005,A01,1.0,Moped,Male,Leisure,Helmet,Yes,NaN,NaN,Unknown,2001.0
1,201800000005,B01,1.0,Car<=3.5T,Male,Leisure,SeatBelt,Yes,NaN,NaN,Unknown,1946.0
2,201800000007,A01,1.0,Car<=3.5T,Male,Other,SeatBelt,Yes,NaN,NaN,Unknown,1996.0

In [79]:
# 데이터 정보 확인
users_test.info()

<class 'pandas.DataFrame'>
RangeIndex: 13372 entries, 0 to 13371
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   AccidentId          13372 non-null  int64
 1   VehicleId           13372 non-null  str
 2   Seat                12024 non-null  float64
 3   Category            13372 non-null  str
 4   Gender              13200 non-null  str
 5   TripReason          10370 non-null  str
 6   SafetyDevice        12774 non-null  str
 7   SafetyDeviceUsed    11664 non-null  str
 8   PedestrianLocation  1082 non-null   str
 9   PedestrianAction    1106 non-null   str
 10  PedestrianCompany   7621 non-null   str
 11  BirthYear           13198 non-null  float64
dtypes: float64(2), int64(1), str(9)
memory usage: 1.2 MB

In [80]:
# 결측치 확인
users_test.isna().sum()

AccidentId                0
VehicleId                 0
Seat                   1348
Category                  0
Gender                  172
TripReason             3002
SafetyDevice            598
SafetyDeviceUsed       1708
PedestrianLocation    12290
PedestrianAction      12266
PedestrianCompany      5751
BirthYear               174
dtype: int64

In [81]:
# 중복 데이터 갯수 확인
print(f"중복된 데이터 갯수: {users_test.duplicated().sum()}")

# AccidentId 기준 중복 데이터 갯수 확인
print(f"'AccidentId'기준 중복된 데이터 갯수: {users_test['AccidentId'].duplicated().sum()}")

# AccidentId + VehicleId + Seat 기준 중복 데이터 갯수 확인 (같은 사건에서 같은 차종과 같은좌석에 앉은사람 중복)
print(f"'AccidentId+VehicleId+Seat' 기준 중복된 데이터 갯수: "
      f"{users_test.duplicated(subset=['AccidentId', 'VehicleId', 'Seat']).sum()}")

중복된 데이터 갯수: 0
'AccidentId'기준 중복된 데이터 갯수: 7593
'AccidentId+VehicleId+Seat' 기준 중복된 데이터 갯수: 181

### 2) Train

In [82]:
# 데이터 확인 
users_train.head(3)

,AccidentId,VehicleId,Seat,Category,Gender,TripReason,SafetyDevice,SafetyDeviceUsed,PedestrianLocation,PedestrianAction,PedestrianCompany,BirthYear
0,201800000001,A01,Driver,Car<=3.5T,M,Leisure,SeatBelt,Yes,NaN,NaN,Unknown,1960.0
1,201800000001,B01,Front Left,Car<=3.5T,M,NaN,SeatBelt,1,NaN,NaN,Unknown,1928.0
2,201800000002,A01,Pilote,Auto,Homme,NaN,SeatBelt,True,NaN,NaN,Unknown,1947.0

In [83]:
# 데이터 정보 확인
users_train.info()

<class 'pandas.DataFrame'>
RangeIndex: 118412 entries, 0 to 118411
Data columns (total 12 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   AccidentId          118412 non-null  int64
 1   VehicleId           118412 non-null  str
 2   Seat                107007 non-null  str
 3   Category            118412 non-null  str
 4   Gender              116749 non-null  str
 5   TripReason          91137 non-null   str
 6   SafetyDevice        113062 non-null  str
 7   SafetyDeviceUsed    104246 non-null  str
 8   PedestrianLocation  8922 non-null    str
 9   PedestrianAction    9155 non-null    str
 10  PedestrianCompany   67696 non-null   str
 11  BirthYear           116759 non-null  str
dtypes: int64(1), str(11)
memory usage: 10.8 MB

In [84]:
# 결측치 확인
users_train.isna().sum()

AccidentId                 0
VehicleId                  0
Seat                   11405
Category                   0
Gender                  1663
TripReason             27275
SafetyDevice            5350
SafetyDeviceUsed       14166
PedestrianLocation    109490
PedestrianAction      109257
PedestrianCompany      50716
BirthYear               1653
dtype: int64

In [85]:
# 중복 데이터 갯수 확인
print(f"중복된 데이터 갯수: {users_train.duplicated().sum()}")

# AccidentId 기준 중복 데이터 갯수 확인
print(f"'AccidentId'기준 중복된 데이터 갯수: {users_train['AccidentId'].duplicated().sum()}")

# AccidentId + VehicleId + Seat 기준 중복 데이터 갯수 확인 (같은 사건에서 같은 차종과 같은좌석에 앉은사람 중복)
print(f"'AccidentId+VehicleId+Seat' 기준 중복된 데이터 갯수: "
      f"{users_train.duplicated(subset=['AccidentId', 'VehicleId', 'Seat']).sum()}")

중복된 데이터 갯수: 0
'AccidentId'기준 중복된 데이터 갯수: 66408
'AccidentId+VehicleId+Seat' 기준 중복된 데이터 갯수: 1115

In [86]:
users_train['Seat'].value_counts(dropna=False)

Seat
Conducteur    17418
Pilote        17287
Driver        17246
Front Left    17223
1             17223
2.0           12969
NaN           11405
3.0            2234
4.0            1835
9.0            1238
7.0            1110
8.0             536
5.0             532
6.0             156
Name: count, dtype: int64

## 데이터 확인 결과
- 중복 확인시 AccidenId가 중복이 확인되었고 이는 사고에 연관된 많은 사람들이 모두 포함되었다는것을 알 수 있다.
- 이는 정상적인 데이터의 범주라고 판단하였고 좀 더 자세한 중복 데이터를 확인하기 위해 데이터 특성값 표기를 통일 한 후 다시한번 확인한다.

#### Seat 컬럼
- 여러형태의 표기방식 (Driver, Pilote, Conducteur, front Left) 을 숫자형으로 통일한다.
- Front Left를 조수석으로 가정할 경우 하나의 차량 내에서 Seat 위치와 VehicleId가 비정상적으로 과도하게 중복으로 발생하므로 운전석으로 판단한다.
- 또한 이 데이터는 프랑스의 데이터로 우측통행 국가로 앞좌석의 왼쪽은 운전석이 되는 구조인것을 확인하였다.

In [87]:
# Seat 고유 값 확인
users_train['Seat'].sort_values().unique()

<StringArray>
[         '1',        '2.0',        '3.0',        '4.0',        '5.0',
        '6.0',        '7.0',        '8.0',        '9.0', 'Conducteur',
     'Driver', 'Front Left',     'Pilote',          nan]
Length: 14, dtype: str

In [88]:
# 매핑 코드 생성
seat_map = {
    'Driver' : '1.0',
    'Pilote' : '1.0',
    'Conducteur' : '1.0',
    'Front Left' : '1.0',
    '1' : "1.0",
}

In [89]:
# 매핑키 적용
users_train['Seat'] = users_train['Seat'].replace(seat_map)

In [90]:
# 변경 고유 값 확인
users_train['Seat'].sort_values().unique()

<StringArray>
['1.0', '2.0', '3.0', '4.0', '5.0', '6.0', '7.0', '8.0', '9.0', nan]
Length: 10, dtype: str

#### Category 컬럼
- 오타, 단위 표기 오류 수정
- 대소문자, 특수기호 통일
- 숫자 단위 표기에서 숫자와 알파벳 혼재 통일

In [91]:
# Category 고유값 확인
users_train['Category'].sort_values().unique()

<StringArray>
[                  'Auto',                'Bicycle',                 'Bicyde',
                    'Bus',                    'Car',              'Car<=3.5T',
                  'Coach',  'LargeCar+Trailer>3.5T',          'LargeCar>7.5T',
     'LargeCar_3.5T-7.5T',          'Light Vehicle',           'Light Vehide',
                  'Moped',       'Motorbike>125cm3',       'Motorbike>l25cm3',
 'Motorbike_50cm3-125cm3', 'Motorbike_50cm3-l25cm3', 'Motorbike_5Ocm3-125cm3',
 'Motorbike_5Ocm3-l25cm3',                  'Other',        'QuadBike<=50cm3',
        'QuadBike<=5Ocm3',         'QuadBike>50cm3',         'QuadBike>5Ocm3',
            'Quadricycle',             'Quadricyde',          'Scooter<50cm3',
          'Scooter<5Ocm3',         'Scooter>125cm3',         'Scooter>l25cm3',
   'Scooter_50cm3-125cm3',   'Scooter_50cm3-l25cm3',   'Scooter_5Ocm3-125cm3',
   'Scooter_5Ocm3-l25cm3',          'SpecialEngine',                'Tractor',
                  'Train',                'Tramway',                  'Truck',
      'Truck+SemiTrailer',                'Utility',                'Voiture']
Length: 42, dtype: str

In [92]:
# test 고유값 확인
users_test['Category'].sort_values().unique()

<StringArray>
[               'Bicycle',                    'Bus',              'Car<=3.5T',
                  'Coach',  'LargeCar+Trailer>3.5T',          'LargeCar>7.5T',
     'LargeCar_3.5T-7.5T',                  'Moped',       'Motorbike>125cm3',
 'Motorbike_50cm3-125cm3',                  'Other',        'QuadBike<=50cm3',
         'QuadBike>50cm3',            'Quadricycle',          'Scooter<50cm3',
         'Scooter>125cm3',   'Scooter_50cm3-125cm3',          'SpecialEngine',
                'Tractor',                  'Train',                'Tramway',
                  'Truck',      'Truck+SemiTrailer',                'Utility']
Length: 24, dtype: str

In [93]:
# 매핑 코드 만들기

vehicle_map = {
    # Car<=3.5T
    "Voiture": "Car<=3.5T",
    "Light Vehide": "Car<=3.5T",
    "Light Vehicle": "Car<=3.5T",
    "Car": "Car<=3.5T",
    "Auto": "Car<=3.5T",

    # Bicycle
    "Bicyde": "Bicycle",

    # Motorbike>125cm3
    "Motorbike>l25cm3": "Motorbike>125cm3",

    # Motorbike_50cm3-125cm3
    "Motorbike_5Ocm3-l25cm3": "Motorbike_50cm3-125cm3",
    "Motorbike_5Ocm3-125cm3": "Motorbike_50cm3-125cm3",
    "Motorbike_50cm3-l25cm3": "Motorbike_50cm3-125cm3",

    # QuadBike<=50cm3
    "QuadBike<=5Ocm3": "QuadBike<=50cm3",

    # QuadBike>50cm3
    "QuadBike>5Ocm3": "QuadBike>50cm3",

    # Quadricycle
    "Quadricyde": "Quadricycle",

    # Scooter<50cm3
    "Scooter<5Ocm3": "Scooter<50cm3",

    # Scooter>125cm3
    "Scooter>l25cm3": "Scooter>125cm3",

    # Scooter_50cm3-125cm3
    "Scooter_50cm3-l25cm3": "Scooter_50cm3-125cm3",
    "Scooter_5Ocm3-125cm3": "Scooter_50cm3-125cm3",
    "Scooter_5Ocm3-l25cm3": "Scooter_50cm3-125cm3"
    
}

In [94]:
# 매핑 코드 적용
users_train['Category'] = users_train['Category'].replace(vehicle_map)

In [95]:
# 매핑 후 카테고리 고유값 확인
print(f"변경 후 카테고리 고유 값:\n{users_train['Category'].sort_values().unique()}")

변경 후 카테고리 고유 값:
<StringArray>
[               'Bicycle',                    'Bus',              'Car<=3.5T',
                  'Coach',  'LargeCar+Trailer>3.5T',          'LargeCar>7.5T',
     'LargeCar_3.5T-7.5T',                  'Moped',       'Motorbike>125cm3',
 'Motorbike_50cm3-125cm3',                  'Other',        'QuadBike<=50cm3',
         'QuadBike>50cm3',            'Quadricycle',          'Scooter<50cm3',
         'Scooter>125cm3',   'Scooter_50cm3-125cm3',          'SpecialEngine',
                'Tractor',                  'Train',                'Tramway',
                  'Truck',      'Truck+SemiTrailer',                'Utility']
Length: 24, dtype: str

#### Gender 컬럼
- 약어, 불어, 영어, 숫자 등 다양한 표기 Male, Female로 통일

In [96]:
# 고유 값 확인
users_train['Gender'].unique()

<StringArray>
['M', 'Homme', 'Male', '1', nan, 'H', '0', 'Femme', 'Female', 'F']
Length: 10, dtype: str

In [97]:
# 매핑 코드 만들기
gender_map = {
    'M': 'Male',
    'H': 'Male',
    'Homme': 'Male',
    'Male': 'Male',
    '1': 'Male',

    'F': 'Female',
    'Femme': 'Female',
    'Female': 'Female',
    '0': 'Female',
}

In [98]:
# 매핑 값 적용
users_train['Gender'] = users_train['Gender'].replace(gender_map)

In [99]:
# 변경 고유 값 확인
users_train['Gender'].unique()

<StringArray>
['Male', nan, 'Female']
Length: 3, dtype: str

#### SafetyDeviceUsed 컬럼
- 영어, 불어, 문자, 숫자, 불타입 등 혼재 Yes, No 로 통일

In [100]:
# 고유 값 확인
users_train['SafetyDeviceUsed'].unique()

<StringArray>
['Yes', '1', 'True', nan, 'Oui', 'Y', 'Unknown', 'N', 'Non', '0', 'False',
 'No']
Length: 12, dtype: str

In [101]:
yes_values = ['Yes', '1', 'True', 'Oui', 'Y']
no_values = ['No', 'N', 'Non', '0', 'False']

users_train['SafetyDeviceUsed'] = users_train['SafetyDeviceUsed'].apply(
    lambda x: 'Yes' if x in yes_values else ('No' if x in no_values else x))

In [102]:
# 변경 고유 값 확인
users_train['SafetyDeviceUsed'].unique()

<StringArray>
['Yes', nan, 'Unknown', 'No']
Length: 4, dtype: str

#### BirthYear 컬럼

- 4자리 숫자로 통일성 유지

**변환 기준 : 2018년에 발생한 데이터라는 점을 고려하여 두 자리 연도는 다음 기준으로 변환했다.**
- 0 ~ 18 → 2000~2018년생
- 19 ~ 99 → 1919~1999년생

In [103]:
users_train['BirthYear'].head(10)

0      1960.0
1      1928.0
2      1947.0
3        65.0
4        37.0
5         NaN
6    REDACTED
7      1982.0
8        11.0
9        40.0
Name: BirthYear, dtype: str

In [104]:
# Int64로 변환하여 연산하기 - 숫자 변환시 문자는 자동 결측처리
users_train['BirthYear'] = pd.to_numeric(users_train['BirthYear'], errors='coerce').astype("Int64")

In [105]:
# 범위 지정하기

# 2000~2018년
mask_0_18 = users_train['BirthYear'].between(0, 18)

# 1919~1999년
mask_19_99 = users_train['BirthYear'].between(19, 99)

In [106]:
# BirthYear를 4자리 연도로 정규화
users_train.loc[mask_0_18, 'BirthYear'] = users_train.loc[mask_0_18, 'BirthYear'] + 2000
users_train.loc[mask_19_99, 'BirthYear'] = users_train.loc[mask_19_99, 'BirthYear'] + 1900

In [107]:
# BirthYear 중 의미를 해석할 수 없는 3자리 값은 결측처리
invalid_mask = (
    users_train["BirthYear"].notna() &
    ((users_train["BirthYear"] < 1000) | (users_train["BirthYear"] > 9999))
)

users_train.loc[invalid_mask, 'BirthYear'] = np.nan

In [108]:
users_train

,AccidentId,VehicleId,Seat,Category,Gender,TripReason,SafetyDevice,SafetyDeviceUsed,PedestrianLocation,PedestrianAction,PedestrianCompany,BirthYear
0,201800000001,A01,1.0,Car<=3.5T,Male,Leisure,SeatBelt,Yes,NaN,NaN,Unknown,1960
1,201800000001,B01,1.0,Car<=3.5T,Male,NaN,SeatBelt,Yes,NaN,NaN,Unknown,1928
2,201800000002,A01,1.0,Car<=3.5T,Male,NaN,SeatBelt,Yes,NaN,NaN,Unknown,1947
3,201800000002,A01,NaN,Car<=3.5T,Male,NaN,Helmet,NaN,OnLane<=OnSidewalk0mCrossing,Crossing,Alone,1965
4,201800000003,A01,1.0,Motorbike>125cm3,Male,Leisure,Helmet,Yes,NaN,NaN,Unknown,1937
...,...,...,...,...,...,...,...,...,...,...,...,...
118407,201800057781,A01,NaN,Car<=3.5T,Male,Other,ChildrenDevice,NaN,OnCrossingWithoutLights,Crossing,Alone,1975
118408,201800057782,A01,1.0,Car<=3.5T,Female,Other,SeatBelt,Yes,NaN,NaN,NaN,1993
118409,201800057782,B01,1.0,Motorbike_50cm3-125cm3,Male,Other,Helmet,Yes,NaN,NaN,NaN,1974
118410,201800057783,A01,1.0,Utility,Female,Other,SeatBelt,Yes,NaN,NaN,NaN,1934
118411,201800057783,B01,1.0,Utility,Male,Other,SeatBelt,Yes,NaN,NaN,NaN,1973

In [109]:
# 문자열로 변환 후 4자리 숫자 패턴이 아닌 것 찾기
mask = ~users_train['BirthYear'].astype(str).str.match(r'^\d{4}(\.0)?$') & users_train['BirthYear'].notna()
users_train[mask]

Empty DataFrame
Columns: [AccidentId, VehicleId, Seat, Category, Gender, TripReason, SafetyDevice, SafetyDeviceUsed, PedestrianLocation, PedestrianAction, PedestrianCompany, BirthYear]
Index: []

In [110]:
users_train['BirthYear'].head(10)

0    1960
1    1928
2    1947
3    1965
4    1937
5    <NA>
6    <NA>
7    1982
8    2011
9    1940
Name: BirthYear, dtype: Int64

#### 중복 데이터 재확인하기
- 데이터의 형식을 통일 시킨 후 데이터의 중복을 확인하여 제거하는 작업진행 (재확인)

In [111]:
# 중복 데이터 갯수 확인
print(f"중복된 데이터 갯수: {users_train.duplicated().sum()}")

# AccidentId 기준 중복 데이터 갯수 확인
print(f"'AccidentId'기준 중복된 데이터 갯수: {users_train['AccidentId'].duplicated().sum()}")

중복된 데이터 갯수: 0
'AccidentId'기준 중복된 데이터 갯수: 66408

# 4. Vehicles

## 데이터 확인

### 1) Test

In [112]:
# 데이터 확인
vehicles_test.head(3)

,AccidentId,VehicleId,Direction,Category,PassengerNumber,FixedObstacle,MobileObstacle,ImpactPoint,Maneuver
0,201800000005,A01,Unknown,Moped,0,NaN,Vehicle,RightFront,PassLeft
1,201800000005,B01,Unknown,Car<=3.5T,0,NaN,Vehicle,LeftFront,Park
2,201800000007,A01,Unknown,Car<=3.5T,0,Post,NaN,LeftSide,NaN

In [113]:
# 데이터 정보 확인
vehicles_test.info()

<class 'pandas.DataFrame'>
RangeIndex: 9893 entries, 0 to 9892
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   AccidentId       9893 non-null   int64
 1   VehicleId        9893 non-null   str
 2   Direction        9880 non-null   str
 3   Category         9893 non-null   str
 4   PassengerNumber  9893 non-null   int64
 5   FixedObstacle    1324 non-null   str
 6   MobileObstacle   8240 non-null   str
 7   ImpactPoint      9357 non-null   str
 8   Maneuver         9131 non-null   str
dtypes: int64(2), str(7)
memory usage: 695.7 KB

In [114]:
# 결측치 확인
vehicles_test.isna().sum()

AccidentId            0
VehicleId             0
Direction            13
Category              0
PassengerNumber       0
FixedObstacle      8569
MobileObstacle     1653
ImpactPoint         536
Maneuver            762
dtype: int64

In [115]:
# 중복 데이터 갯수 확인
print(f"중복된 데이터 갯수: {vehicles_test.duplicated().sum()}")

중복된 데이터 갯수: 0

In [116]:
# AccidentId 기준 중복 데이터 갯수 확인
print(f"'AccidentId'기준 중복된 데이터 갯수: {vehicles_test['AccidentId'].duplicated().sum()}")

'AccidentId'기준 중복된 데이터 갯수: 4114

In [117]:
# 데이터 타입 기준 정의
vehicles_type_reference = {
    # 식별자
    "AccidentId": "int64",
    "VehicleId": "string",

    # 범주형
    "Direction": "string",
    "Category": "string",
    "FixedObstacle": "string",
    "MobileObstacle": "string",
    "ImpactPoint": "string",
    "Maneuver": "string",
    
    # 탑승자 수
    "PassengerNumber": "Int64"
}

# 타입 적용
vehicles_test = vehicles_test.astype(vehicles_type_reference)

In [118]:
# 데이터 변경 정보 확인
vehicles_test.info()

<class 'pandas.DataFrame'>
RangeIndex: 9893 entries, 0 to 9892
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   AccidentId       9893 non-null   int64
 1   VehicleId        9893 non-null   string
 2   Direction        9880 non-null   string
 3   Category         9893 non-null   string
 4   PassengerNumber  9893 non-null   Int64
 5   FixedObstacle    1324 non-null   string
 6   MobileObstacle   8240 non-null   string
 7   ImpactPoint      9357 non-null   string
 8   Maneuver         9131 non-null   string
dtypes: Int64(1), int64(1), string(7)
memory usage: 705.4 KB

### 2) Train

In [119]:
# 데이터 확인
vehicles_train.head(3)

,AccidentId,VehicleId,Direction,Category,PassengerNumber,FixedObstacle,MobileObstacle,ImpactPoint,Maneuver
0,201800000001,V01,Unk,Car<=3.5T,0,NaN,Vehicle,Front Right,Turning Left
1,201800000001,Car_01,?,Car<=3.5T,0,NaN,Blue Ford,LeftFront,NoDirectionChange
2,201800000002,V01,Unk,Car<=3.5T,0,NaN,Pedestrian,NaN,NoDirectionChange

In [120]:
# 데이터 정보 확인
vehicles_train.info()

<class 'pandas.DataFrame'>
RangeIndex: 88983 entries, 0 to 88982
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   AccidentId       88983 non-null  int64
 1   VehicleId        88983 non-null  str
 2   Direction        88864 non-null  str
 3   Category         88983 non-null  str
 4   PassengerNumber  88983 non-null  int64
 5   FixedObstacle    12792 non-null  str
 6   MobileObstacle   73314 non-null  str
 7   ImpactPoint      84125 non-null  str
 8   Maneuver         81811 non-null  str
dtypes: int64(2), str(7)
memory usage: 6.1 MB

In [121]:
# 결측치 확인
vehicles_train.isna().sum()

AccidentId             0
VehicleId              0
Direction            119
Category               0
PassengerNumber        0
FixedObstacle      76191
MobileObstacle     15669
ImpactPoint         4858
Maneuver            7172
dtype: int64

In [122]:
# 중복 데이터 갯수 확인
print(f"중복된 데이터 갯수: {vehicles_train.duplicated().sum()}")

# AccidentId 기준 중복 데이터 갯수 확인
print(f"'AccidentId'기준 중복된 데이터 갯수: {vehicles_train['AccidentId'].duplicated().sum()}")

중복된 데이터 갯수: 176
'AccidentId'기준 중복된 데이터 갯수: 36979

## 데이터 확인 결과
- VehicleId, Category 컬럼은 특성값의 통일성이 전혀 없고 손상도가 심한것으로 판단하였다.
- 다만 Users 데이터 셋에서 동일한 데이터가 존재하고 손상도가 높아 컬럼자체를 제거한다.
- 중복데이터는 컬럼의 특성값들을 통일시킨 후 제거한다.

In [123]:
# VehicleId 삭제(Drop) - test, train 모두 삭제
vehicles_train = vehicles_train.drop(columns=["VehicleId"])
vehicles_test = vehicles_test.drop(columns=["VehicleId"])

In [124]:
# Category 삭제(Drop) - test, train 모두 삭제
vehicles_train = vehicles_train.drop(columns=["Category"])
vehicles_test = vehicles_test.drop(columns=["Category"])

In [125]:
# 삭제 확인
vehicles_train.head(3)

,AccidentId,Direction,PassengerNumber,FixedObstacle,MobileObstacle,ImpactPoint,Maneuver
0,201800000001,Unk,0,NaN,Vehicle,Front Right,Turning Left
1,201800000001,?,0,NaN,Blue Ford,LeftFront,NoDirectionChange
2,201800000002,Unk,0,NaN,Pedestrian,NaN,NoDirectionChange

#### Direction 컬럼
- 특수문자 삭제 처리
- 프랑스어, 영어 등 다양한 표기를 통일

In [126]:
# 고유값 확인
vehicles_train['Direction'].unique()

<StringArray>
['Unk', '?', 'Unknown', 'Inconnu', 'Increasing', 'Decreasing', nan]
Length: 7, dtype: str

In [127]:
# 매핑키 생성
Direction_map = {
    "Unk": "Unknown",
    "?": "Unknown",
    "Inconnu": "Unknown"
}

# 타입 적용
vehicles_train['Direction'] = vehicles_train['Direction'].replace(Direction_map)

In [128]:
# 고유값 변경 확인
vehicles_train['Direction'].unique()

<StringArray>
['Unknown', 'Increasing', 'Decreasing', nan]
Length: 4, dtype: str

#### MobileObstacle 컬럼
- 충돌한 물체가 어떤것인지 나타낸다.
- 차량의 기종들은 모두 vehicles로 바꿔 표기의 통일성을 맞춘다.
- 이 컬럼은 충돌한 물체의 범주를 나타내는것으로 도로위를 달리는 차량은 'Vehicle' 범주로 변환한다.

In [129]:
# 고유값 확인
vehicles_train['MobileObstacle'].unique()

<StringArray>
[       'Vehicle',      'Blue Ford',     'Pedestrian',              nan,
          'Other',     'Red Toyota',     'Motorcycle',          'Truck',
      'White Van',     'WildAnimal', 'DomesticAnimal',  'RailedVehicle']
Length: 12, dtype: str

In [130]:
# Test 고유값 확인
vehicles_test['MobileObstacle'].unique()

<StringArray>
[       'Vehicle',             <NA>,     'Pedestrian',          'Other',
  'RailedVehicle',     'WildAnimal', 'DomesticAnimal']
Length: 7, dtype: string

In [131]:
# 매핑키 생성
MobileObstacle_map = {
    "White Van": "Vehicle",
    "Truck": "Vehicle",
    "Red Toyota": "Vehicle",
    "Motorcycle": "Vehicle",
    "Blue Ford": "Vehicle"
}

# 타입 적용
vehicles_train['MobileObstacle'] = vehicles_train['MobileObstacle'].replace(MobileObstacle_map)

In [132]:
# 변경된 고유값 확인
vehicles_train['MobileObstacle'].unique()

<StringArray>
[       'Vehicle',     'Pedestrian',              nan,          'Other',
     'WildAnimal', 'DomesticAnimal',  'RailedVehicle']
Length: 7, dtype: str

#### ImpactPoint 컬럼

- 같은 의미의 값이 영어, 불어, 약어 등 존재 
- 라벨 표기를 통일한다.

In [133]:
# 고유값 확인
vehicles_train['ImpactPoint'].unique()

<StringArray>
['Front Right',   'LeftFront',           nan,       'Front',    'LeftSide',
   'RightSide', 'Avant Droit',        'Back',    'LeftBack', 'Right Front',
    'Multiple',   'RightBack',          'RF']
Length: 13, dtype: str

In [134]:
# 매핑키 생성
ImpactPoint_map = {
    "Right Front": "RightFront",
    "Front Right": "RightFront",
    "RF": "RightFront",
    "Avant Droit": "RightFront"
}

# 타입 적용
vehicles_train['ImpactPoint'] = vehicles_train['ImpactPoint'].replace(ImpactPoint_map)

In [135]:
# 변경 고유값 확인
vehicles_train['ImpactPoint'].unique()

<StringArray>
['RightFront',  'LeftFront',          nan,      'Front',   'LeftSide',
  'RightSide',       'Back',   'LeftBack',   'Multiple',  'RightBack']
Length: 10, dtype: str

#### ImpactPoint 컬럼

- 오타, 다국어, 약어 등의 표기 통일

In [136]:
# 고유값 확인
vehicles_train['Maneuver'].unique()

<StringArray>
[         'Turning Left',     'NoDirectionChange',         'Virage Gauche',
                'Parked',             'Avoidance',                     nan,
              'PassLeft',                    'TL',          'Turn To Left',
              'WrongWay',               'Stopped',           'Tuming Left',
   'SameDirectionOrLane',          'SwerveToLeft',          'Turring Left',
           'Turned Left',             'Insertion',             'CrossLane',
           'TurnToRight',         'SwerveToRight',           'UTurnInLane',
                  'Park',     'ChangeToRightLane',      'ChangeToLeftLane',
               'Reverse',            'CrossStrip',             'PassRight',
          'BetweenLanes',            'TumToRight',           'Tum To Left',
            'Tumed Left',              'OpenDoor', 'BusLaneWrongDirection',
  'BusLaneSameDirection',            'UTumInLane']
Length: 35, dtype: str

In [137]:
# 매핑키 생성

maneuver_map = {
    # U-Turn 오타
    'UTumInLane': 'UTurnInLane',

    # 좌회전(Left Turn) 관련
    'Virage Gauche': 'TurnToLeft',
    'Turring Left': 'TurnToLeft',
    'Turning Left': 'TurnToLeft',
    'Turned Left': 'TurnToLeft',
    'Turn To Left': 'TurnToLeft',
    'Tuming Left': 'TurnToLeft',
    'Tumed Left': 'TurnToLeft',
    'Tum To Left': 'TurnToLeft',
    'TL': 'TurnToLeft',

    # 우회전(Right Turn) 관련
    'TumToRight': 'TurnToRight' 
}

# 타입 적용
vehicles_train['Maneuver'] = vehicles_train['Maneuver'].replace(maneuver_map)

In [138]:
# 변경 고유값 확인
vehicles_train['Maneuver'].unique()

<StringArray>
[           'TurnToLeft',     'NoDirectionChange',                'Parked',
             'Avoidance',                     nan,              'PassLeft',
              'WrongWay',               'Stopped',   'SameDirectionOrLane',
          'SwerveToLeft',             'Insertion',             'CrossLane',
           'TurnToRight',         'SwerveToRight',           'UTurnInLane',
                  'Park',     'ChangeToRightLane',      'ChangeToLeftLane',
               'Reverse',            'CrossStrip',             'PassRight',
          'BetweenLanes',              'OpenDoor', 'BusLaneWrongDirection',
  'BusLaneSameDirection']
Length: 25, dtype: str

In [139]:
# 데이터 타입 기준 정의

vehicles_type_reference = {
    # 식별자
    "AccidentId": "int64",

    # 범주형
    "Direction": "string",
    "FixedObstacle": "string",
    "MobileObstacle": "string",
    "ImpactPoint": "string",
    "Maneuver": "string",
    
    # 탑승자 수
    "PassengerNumber": "Int64"
}

# 타입 적용
vehicles_train = vehicles_train.astype(vehicles_type_reference)

In [140]:
# 데이터 변경 정보 확인
vehicles_train.info()

<class 'pandas.DataFrame'>
RangeIndex: 88983 entries, 0 to 88982
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   AccidentId       88983 non-null  int64
 1   Direction        88864 non-null  string
 2   PassengerNumber  88983 non-null  Int64
 3   FixedObstacle    12792 non-null  string
 4   MobileObstacle   73314 non-null  string
 5   ImpactPoint      84125 non-null  string
 6   Maneuver         81811 non-null  string
dtypes: Int64(1), int64(1), string(5)
memory usage: 4.8 MB

### 중복 데이터 확인

In [141]:
# 중복 데이터 갯수 확인
print(f"중복된 데이터 갯수: {vehicles_train.duplicated().sum()}")

중복된 데이터 갯수: 2505

In [142]:
# 중복 데이터 삭제 하기
vehicles_train = vehicles_train.drop_duplicates()

In [143]:
# 삭제 후 중복 데이터 갯수 확인
print(f"중복된 데이터 갯수: {vehicles_train.duplicated().sum()}")

# AccidentId 기준 중복 데이터 갯수 확인
print(f"'AccidentId'기준 중복된 데이터 갯수: {vehicles_train['AccidentId'].duplicated().sum()}")

중복된 데이터 갯수: 0
'AccidentId'기준 중복된 데이터 갯수: 34474

# 최종 데이터 셋 저장하기

In [144]:
users_train

,AccidentId,VehicleId,Seat,Category,Gender,TripReason,SafetyDevice,SafetyDeviceUsed,PedestrianLocation,PedestrianAction,PedestrianCompany,BirthYear
0,201800000001,A01,1.0,Car<=3.5T,Male,Leisure,SeatBelt,Yes,NaN,NaN,Unknown,1960
1,201800000001,B01,1.0,Car<=3.5T,Male,NaN,SeatBelt,Yes,NaN,NaN,Unknown,1928
2,201800000002,A01,1.0,Car<=3.5T,Male,NaN,SeatBelt,Yes,NaN,NaN,Unknown,1947
3,201800000002,A01,NaN,Car<=3.5T,Male,NaN,Helmet,NaN,OnLane<=OnSidewalk0mCrossing,Crossing,Alone,1965
4,201800000003,A01,1.0,Motorbike>125cm3,Male,Leisure,Helmet,Yes,NaN,NaN,Unknown,1937
...,...,...,...,...,...,...,...,...,...,...,...,...
118407,201800057781,A01,NaN,Car<=3.5T,Male,Other,ChildrenDevice,NaN,OnCrossingWithoutLights,Crossing,Alone,1975
118408,201800057782,A01,1.0,Car<=3.5T,Female,Other,SeatBelt,Yes,NaN,NaN,NaN,1993
118409,201800057782,B01,1.0,Motorbike_50cm3-125cm3,Male,Other,Helmet,Yes,NaN,NaN,NaN,1974
118410,201800057783,A01,1.0,Utility,Female,Other,SeatBelt,Yes,NaN,NaN,NaN,1934
118411,201800057783,B01,1.0,Utility,Male,Other,SeatBelt,Yes,NaN,NaN,NaN,1973

In [145]:
# Accidents

accidents_test.to_csv("./data/preprocessed/Accidents_test_preprocessed.csv",
                       index=False,
                       encoding="utf-8-sig")

accidents_train.to_csv("./data/preprocessed/Accidents_train_preprocessed.csv",
                       index=False,
                       encoding="utf-8-sig")

In [146]:
# Places

places_test.to_csv("./data/preprocessed/places_test_preprocessed.csv",
                       index=False,
                       encoding="utf-8-sig")

places_train.to_csv("./data/preprocessed/places_train_preprocessed.csv",
                       index=False,
                       encoding="utf-8-sig")

In [147]:
# Users

users_test.to_csv("./data/preprocessed/users_test_preprocessed.csv",
                       index=False,
                       encoding="utf-8-sig")

users_train.to_csv("./data/preprocessed/users_train_preprocessed.csv",
                       index=False,
                       encoding="utf-8-sig")

In [148]:
# Vehicles

vehicles_test.to_csv("./data/preprocessed/vehicles_test_preprocessed.csv",
                       index=False,
                       encoding="utf-8-sig")

vehicles_train.to_csv("./data/preprocessed/vehicles_train_preprocessed.csv",
                       index=False,
                       encoding="utf-8-sig")